language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-19mode

  - ruby-head
  - jruby-19mode

script: bundle exec rspec
before_install:
  - gem update bundler
before_script:
  - bundle exec gem list

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
